#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class AsteriskInfo < Model

    attr_reader :build, :system, :config, :status

    def build=(val)
      @build ||= BuildInfo.new(val)
    end

    def system=(val)
      @system ||= SystemInfo.new(val)
    end

    def config=(val)
      @config ||= ConfigInfo.new(val)
    end

    def status=(val)
      @status ||= StatusInfo.new(val)
    end


  end
end
