#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class BridgeBlindTransfer < Event

    attr_reader :channel, :replace_channel, :transferee, :exten, :context, :result, :is_external, :bridge

    def channel=(val)
      @channel ||= Channel.new(val)
    end

    def replace_channel=(val)
      @replace_channel ||= Channel.new(val)
    end

    def transferee=(val)
      @transferee ||= Channel.new(val)
    end

    def bridge=(val)
      @bridge ||= Bridge.new(val)
    end


  end
end
