#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class BridgeCreated < Event

    attr_reader :bridge

    def bridge=(val)
      @bridge ||= Bridge.new(val)
    end


  end
end
