#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class BridgeAttendedTransfer < Event

    attr_reader :transferer_first_leg, :transferer_second_leg, :replace_channel, :transferee, :transfer_target, :result, :is_external, :transferer_first_leg_bridge, :transferer_second_leg_bridge, :destination_type, :destination_bridge, :destination_application, :destination_link_first_leg, :destination_link_second_leg, :destination_threeway_channel, :destination_threeway_bridge

    def transferer_first_leg=(val)
      @transferer_first_leg ||= Channel.new(val)
    end

    def transferer_second_leg=(val)
      @transferer_second_leg ||= Channel.new(val)
    end

    def replace_channel=(val)
      @replace_channel ||= Channel.new(val)
    end

    def transferee=(val)
      @transferee ||= Channel.new(val)
    end

    def transfer_target=(val)
      @transfer_target ||= Channel.new(val)
    end

    def transferer_first_leg_bridge=(val)
      @transferer_first_leg_bridge ||= Bridge.new(val)
    end

    def transferer_second_leg_bridge=(val)
      @transferer_second_leg_bridge ||= Bridge.new(val)
    end

    def destination_link_first_leg=(val)
      @destination_link_first_leg ||= Channel.new(val)
    end

    def destination_link_second_leg=(val)
      @destination_link_second_leg ||= Channel.new(val)
    end

    def destination_threeway_channel=(val)
      @destination_threeway_channel ||= Channel.new(val)
    end

    def destination_threeway_bridge=(val)
      @destination_threeway_bridge ||= Bridge.new(val)
    end


  end
end
