#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class ChannelUserevent < Event

    attr_reader :eventname, :channel, :bridge, :endpoint, :userevent

    def channel=(val)
      @channel ||= Channel.new(val)
    end

    def bridge=(val)
      @bridge ||= Bridge.new(val)
    end

    def endpoint=(val)
      @endpoint ||= Endpoint.new(val)
    end

    def userevent=(val)
      @userevent ||= object.new(val)
    end


  end
end
