#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class Dial < Event

    attr_reader :caller, :peer, :forward, :forwarded, :dialstring, :dialstatus

    def caller=(val)
      @caller ||= Channel.new(val)
    end

    def peer=(val)
      @peer ||= Channel.new(val)
    end

    def forwarded=(val)
      @forwarded ||= Channel.new(val)
    end


  end
end
