#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari-client ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class LiveRecording < Model

    attr_reader :name, :format, :target_uri, :state, :duration, :talking_duration, :silence_duration, :cause


  end
end
