#------------------------------------------------------------------------------
#
#  WARNING !
#
#  This is a generated file. DO NOT EDIT THIS FILE! Your changes will
#  be lost the next time this file is regenerated.
#
#  This file was generated using asterisk-ari ruby gem.
#
#------------------------------------------------------------------------------

module Ari
  class TextMessage < Model

    attr_reader :from, :to, :body, :variables

    def variables=(val)
      @variables ||= TextMessageVariable.new(val)
    end


  end
end
